linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck

linters-settings:
  errcheck:
    check-blank: true
    check-type-assertions: true

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
